#!/usr/bin/env bash

. cluster_topology.sh

echo "Resetting cluster" > /tmp/$USER-clreset.log

cat $SLAVES_FILE | while read line;
do
  echo "$line" >> /tmp/$USER-clreset.log
  ssh $line \
   'sudo rm -rf /tmp/hadoop-ucare/* ; rm -rf /mnt/extra/dfs-ucare/* ;'  >> /tmp/$USER-clreset.log
done

cat /tmp/$USER-clreset.log
