#!/bin/bash

. cluster_topology.sh

echo "Initial cluster setup" > /tmp/$USER-clsetup.log

cat $SLAVES_FILE | while read line;
do
  echo $line >> /tmp/$USER-clsetup.log
  ssh -t $line \
   "sudo rm -r /tmp/hadoop-ucare /mnt/extra/dfs-ucare; \
    sudo mkdir -p /tmp/hadoop-ucare /mnt/extra/dfs-ucare; \
    sudo chgrp -R $SUPERGROUP /tmp/hadoop-ucare /mnt/extra;
    sudo chmod -R 774 /tmp/hadoop-ucare /mnt/extra;"  >> /tmp/$USER-clsetup.log
done

cat /tmp/$USER-clsetup.log
